server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8080
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<segment>/?.*), /api/users$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG